"""VTU Skills - Simple predefined list (no embeddings needed)"""

VTU_SKILLS = [
    "3D PRINTING CONCEPTS, DESIGN AND PRINTING",
    "Adobe Illustrator",
    "Adobe Indesign",
    "Adobe Photoshop",
    "Android Studio",
    "Angular",
    "AWS",
    "Azure",
    "BIM CONCEPTS WITH MEP AND PRODUCT DESIGN",
    "BIM FOR ARCHITECTURE",
    "BIM FOR CONSTRUCTION",
    "BIM FOR HIGHWAY ENGINEERING",
    "BIM FOR STRUCTURES",
    "Business Management",
    "C++",
    "CakePHP",
    "Canva",
    "Cassandra",
    "Circuit Design",
    "Cloud access control",
    "CodeIgniter",
    "computer vision",
    "CSS",
    "D3.js",
    "Data encryption",
    "Data modeling",
    "Data visualization",
    "Database design",
    "Design with FPGA",
    "DevOps",
    "DHCP",
    "Digital Design",
    "Docker",
    "Economics",
    "Embedded Systems",
    "Figma",
    "FilamentPHP",
    "Finance",
    "Firewall configuration",
    "Flutter",
    "Git",
    "Godot",
    "Google Cloud",
    "HTML",
    "IaaS",
    "Indexing",
    "Intelligent Machines",
    "INTERIOR AND EXTERIOR DESIGN",
    "IoT",
    "Java",
    "JavaScript",
    "Keras",
    "Kotlin",
    "Kubernetes",
    "LAN",
    "Laravel",
    "Layout Design",
    "Machine learning",
    "Manufacturing",
    "Marketing",
    "MongoDB",
    "MySQL",
    "Natural language processing",
    "Network architecture",
    "Node.js",
    "NoSQL",
    "Objective-C",
    "PaaS",
    "PHP",
    "Physical Design",
    "PostgreSQL",
    "Power BI",
    "PRODUCT DESIGN & 3D PRINTING",
    "PRODUCT DESIGN & MANUFACTURING",
    "Python",
    "PyTorch",
    "React",
    "React.js",
    "Ruby on Rails",
    "SaaS",
    "scikit-learn",
    "SEO",
    "SQL",
    "Statistical analysis",
    "Swift",
    "Tableau",
    "TCP/IP",
    "TensorFlow",
    "TypeScript",
    "UI/UX",
    "Verification & Validations",
    "VLSI Design",
    "VPNs",
    "Vue.js",
    "WAN",
    "WordPress",
    "Xamarin",
    "Xcode"
]


def get_skills_list():
    """Get the complete list of VTU skills"""
    return VTU_SKILLS


def format_skills_for_prompt():
    """Format skills list for LLM prompt"""
    return "\n".join([f"- {skill}" for skill in VTU_SKILLS])
